# fly.toml app configuration file generated for plugin-hub-ai on 2023-05-17T16:41:14+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "plugin-hub-ai"
primary_region = "den"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[mounts]
source = "data"
destination = "/data"
